name: Build and Publish (Frontend)

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
    paths:
      - ./frontend/**
  # run it during pull request
  pull_request:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.40.1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install --legacy-peer-deps
      - run: npm run build --if-present
        env:
          CI: false
      - name: Copy to server
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          local: 'dist'
          host: ${{ secrets.SERVER_IP }}
          port: 22
          remote: '../../var/lib/docker/volumes/tessie-tracker-frontend/_data'
          username: ${{ secrets.HETZNER_USERNAME }}
          password: ${{ secrets.HETZNER_PASSWORD }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
